spring:
  datasource:
    url: jdbc:mysql://localhost:3306/three-weeks?
    username: root
    password: rootroot
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    database: mysql
    show_sql: true
    hibernate.ddl-auto: update